[project]
name = "omni-webui"
version = "0.1.0"
description = "An open-source web interface for LLM Chatbot."
readme = "README.md"
requires-python = ">=3.11, <3.12.0a1"
dependencies = [
    "aiosqlite>=0.20.0",
    "anyio[trio]>=4.7.0",
    "asyncpg>=0.30.0",
    "sqlalchemy[asyncio]>=2.0.32",
    "sqlmodel>=0.0.22",
    "open-webui>=0.4.7",
    "pydantic-settings>=2.6.1",
]

[project.scripts]
omni-webui = "omni_webui.__main__:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["omni_webui"]

[dependency-groups]
dev = [
    "gitlint>=0.20.0.dev48",
    "pre-commit>=4.0.1",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
]

[tool.ruff.lint]
extend-select = ["I"]

[tool.pyright]
venvPath = "."
venv = ".venv"
