apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: omni-webui
  name: omni-webui-pvc
  namespace: omni-webui
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi